config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Create
  get '/tasks/new', to: 'tasks#new', as: :new
  post '/tasks', to: 'tasks#create'

  # Read
  get '/tasks', to: 'tasks#index'
  get '/tasks/:id', to: 'tasks#show', as: :task

  # Update
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch '/tasks/:id', to: 'tasks#update'

  # Delete
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete_task

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  # read
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      redirect_to tasks_new_path
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      redirect_to edit_task_path(@task)
    end
  end

  def destroy
    if @task.destroy
      redirect_to tasks_path, status: :see_other
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= form_tag(class: "") %>
  <div class="mb-3">
  <%= f.label(:title, class: "form-label") %>
  <%= f.text_field(:title, class: "form-control") %>
  </div>
  <div class="mb-3">
  <%= f.label(:details, class: "form-label") %>
  <%= f.text_area(:details, class: "form-control") %>
  </div>
  <div>
  <% if params[:action] == "edit" %>

    <%= f.check_box(:completed) %>
    <%= f.label(:completed, "Completed") %>
  <% end %>
  </div>
  <%= f.submit(class: "btn btn-primary mt-4") %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks <i class="fa-regular fa-square-check"></i></h1>
<ul>
<% @tasks.each do |task| %>
  <li>
    <i class="<%= task.completed ? "fa-regular fa-square-check" : "fa-regular fa-square" %>"></i>
    <%= link_to task.title, task_path(task) %>
    <%= link_to "✏️", edit_task_path(task) %>
    <%= link_to "🗑", delete_task_path(task),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </li>
<% end %>
</ul>
<%= link_to "✚ add new task", new_path %>

app/views/tasks/new.html.erb
<div class="container mt-5">
  <h1>New Task</h1>
  <%= render "form", task: @task %>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p>
<% if @task.completed %>
  This task is completed.
<% else %>
  This task is not yet completed.
<% end %>
</p>
<p><%= link_to "Back to list", tasks_path %></p>